version: '3'

services:
  fluentd:
    image: fluent-mongo-image:latest
    volumes:
      - ./config:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
    networks:
      - iothome-network

networks:
  iothome-network:
    name: iothome-network
    external: true
